### ISSUE TITLE
 AT command reference version confusion

### ISSUE THREAD

**Issue by vstemen** [4IceG/RM520N-GL#2]
Hi.  The AT commands manuals show the following versions for download.

V1.0 (2022-08-12)
V1.0 (2023-07-31)
V1.2 (2021-08-09)
V1.1 (2020-10-09)

Two completely different dates, same version 1.0.
Also, why does V1.0 have a much newer date than V1.2?
V1.2 is the only one that does not show "Status: Preliminary" in the manual, but it is dated
2 years older than V1.0. 

Which one is really the most up to date version of the manual that we should use?

**Comment by 4IceG** [comment]
Hi @vstemen , 
@iamromulan could you explain which file is worth using?

**Comment by iamromulan** [comment]
@vstemen @4IceG 

Quectel has always done things like this. Lots of changing the direction of how they want to layout the features and commands of their modems. (hence the different versions and dates). Here's what I would do. Correlate the date of your firmware you are running with an AT command manual. I just ignore the version numbers and stick with paying attention to the date. Firmware release notes usually show what AT commands are added /removed. 

No one AT manual usually gives you a complete picture of everything you can do. That's why all the manuals are included. I'm sure there's more undocumented commands we don't know about as well.

**Comment by vstemen** [comment]
OK.  Thanks.

Manual Version 1.2 seems to be the only one that documents the commands to control ethernet port (i.e. +QETH), which is weird since it is dated older than both the V1.0 manuals.
